### ISSUE TITLE
XML Special Characters Not Escaped

### ISSUE THREAD

**Issue by bricakeld** [Simon-Initiative/xlsx-to-oli#2]
**Describe the bug**
If special characters such as `&` are used within the content of the excel and word files, the resulting XML file is not well-formed.

**To Reproduce**
1. Submit a valid excel file with the use of `&` in a feedback description or in a question choice.
2. Open the resulting XML
3. See error

**Expected behavior**
The converter should escape and replace special characters with their corresponding tags. e.g. `&#038;` for `&`

**Comment by darrensiegel** [comment]
This is now fixed and available in the 0.0.9 release.
